// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"
)

const listBookingsByRoom = `-- name: ListBookingsByRoom :many
SELECT id, room_id, start_date, end_date, status
FROM bookings
WHERE room_id = $1
ORDER BY start_date DESC
LIMIT $2
`

type ListBookingsByRoomParams struct {
	RoomID int32 `json:"room_id"`
	Limit  int32 `json:"limit"`
}

type ListBookingsByRoomRow struct {
	ID        int32     `json:"id"`
	RoomID    int32     `json:"room_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Status    string    `json:"status"`
}

func (q *Queries) ListBookingsByRoom(ctx context.Context, arg ListBookingsByRoomParams) ([]ListBookingsByRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRoom, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByRoomRow
	for rows.Next() {
		var i ListBookingsByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
