// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    room_number, type, price, status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, room_number, type, price, status, created_at, updated_at
`

type CreateRoomParams struct {
	RoomNumber string `json:"room_number"`
	Type       string `json:"type"`
	Price      int64  `json:"price"`
	Status     string `json:"status"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.RoomNumber,
		arg.Type,
		arg.Price,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Type,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, room_number, type, price, status, created_at, updated_at FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id int32) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Type,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByNumber = `-- name: GetRoomByNumber :one
SELECT id, room_number, type, price, status, created_at, updated_at FROM rooms
WHERE room_number = $1 LIMIT 1
`

func (q *Queries) GetRoomByNumber(ctx context.Context, roomNumber string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByNumber, roomNumber)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Type,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableRooms = `-- name: ListAvailableRooms :many
SELECT id, room_number, type, price, status, created_at, updated_at FROM rooms
WHERE 
    status = 'available' AND
    ($1::text IS NULL OR type = $1) AND
    ($2::bigint IS NULL OR price >= $2) AND
    ($3::bigint IS NULL OR price <= $3) AND
    id NOT IN (
        SELECT room_id FROM bookings
        WHERE status = 'confirmed'
        AND NOT (end_date <= $4 OR start_date >= $5)
    )
ORDER BY room_number
LIMIT $7 OFFSET $6
`

type ListAvailableRoomsParams struct {
	Type        sql.NullString `json:"type"`
	MinPrice    sql.NullInt64  `json:"min_price"`
	MaxPrice    sql.NullInt64  `json:"max_price"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

func (q *Queries) ListAvailableRooms(ctx context.Context, arg ListAvailableRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableRooms,
		arg.Type,
		arg.MinPrice,
		arg.MaxPrice,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.RoomNumber,
			&i.Type,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, room_number, type, price, status, created_at, updated_at FROM rooms
WHERE 
    ($3::text IS NULL OR type = $3) AND
    ($4::bigint IS NULL OR price >= $4) AND
    ($5::bigint IS NULL OR price <= $5)
ORDER BY room_number
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
	Type     sql.NullString `json:"type"`
	MinPrice sql.NullInt64  `json:"min_price"`
	MaxPrice sql.NullInt64  `json:"max_price"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.MinPrice,
		arg.MaxPrice,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.RoomNumber,
			&i.Type,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET 
    room_number = $2,
    type = $3,
    price = $4,
    status = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, room_number, type, price, status, created_at, updated_at
`

type UpdateRoomParams struct {
	ID         int32  `json:"id"`
	RoomNumber string `json:"room_number"`
	Type       string `json:"type"`
	Price      int64  `json:"price"`
	Status     string `json:"status"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.RoomNumber,
		arg.Type,
		arg.Price,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Type,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms
SET 
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, room_number, type, price, status, created_at, updated_at
`

type UpdateRoomStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoomStatus, arg.ID, arg.Status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.Type,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
