info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: get string hello world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello World
      tags:
      - root
  /health:
    get:
      consumes:
      - application/json
      description: get database health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - root
swagger: "2.0"
